<?php
/**
 * Created by IntelliJ IDEA.
 * User: SurferKAT
 * Date: 20-06-2018
 * Time: 16:55
 */

class LunchReserveController extends ModuleAdminController  {

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function initContent()
    {
        return parent::initContent(); // TODO: Change the autogenerated stub
        $this->setTemplate('admin_panel.tpl');

    }


}